### ISSUE TITLE
New fullscreen lightbox needs theming

### ISSUE THREAD

**Issue by terminalmage** [laCour/slack-night-mode#36]
Can be seen whenever clicking on an image in Slack.

**Comment by laCour** [comment]
Sounds like you just need an update, this was fixed in #34. Let me know if updating resolves this!

**Comment by terminalmage** [comment]
Style is showing as up-to-date in Stylish, and the lightbox is still bright white.

**Comment by laCour** [comment]
Not too sure then, you may want to try removing the style then installing it again.

**Comment by terminalmage** [comment]
Nope, that didn't work either. [userstyles.org](https://userstyles.org/styles/101971/slack-night-mode) still shows that the style was last updated on December 6th, while #34 was fixed on the 17th... are you sure you actually pushed the fix?

**Comment by terminalmage** [comment]
When I say "pushed", I mean pushed to userstyles.org so that Stylish can pick up the update.

**Comment by laCour** [comment]
Ah got it. The aubergine variant has been deprecated on Userstyles due to being restricted to 100KB. It's still available here: https://github.com/laCour/slack-night-mode/blob/master/css/variants/aubergine.css

The black variant doesn't have this limit: https://userstyles.org/styles/117475/slack-night-mode-black

I can ask to have the limit lifted if you prefer the aubergine variant.

**Comment by terminalmage** [comment]
yeah I do prefer the purple color to the black.

**Comment by laCour** [comment]
Sounds good, I've asked to have the limit lifted. I'll let you know when that happens.

**Comment by terminalmage** [comment]
Thanks!

**Comment by laCour** [comment]
The limit has been lifted, and I've released the update: https://userstyles.org/styles/101971/slack-night-mode

**Comment by terminalmage** [comment]
Cool, I see the update. Sorry to be a bother though, but the title of the picture is still dark grey, should be updated to a lighter color.

**Comment by laCour** [comment]
No bother at all, thanks for letting me know. I wouldn't have noticed otherwise. #37
